version: '3.1'

services:
  psql:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  redis:
    image: redis:7.2-alpine
    restart: on-failure
    ports:
      - 6379:6379